version: '3.8'

services:
  # Configuration MySQL
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ecommerce_dev
      POSTGRES_PASSWORD: 3c0mMerce
      POSTGRES_DB: ecommerce
      #MYSQL_ROOT_PASSWORD: 4db4ea9f1
      #MYSQL_USER: ecommerce_dev
      #MYSQL_PASSWORD: 3c0mMerce
      #MYSQL_DATABASE: ecommerce
      #MYSQL_TCP_PORT: 3309
      #TZ: Europe/Paris
    volumes:
      - db:/var/lib/postgresql/data
  # Configuration PHP
  php:
    container_name: mangamania
    build:
      context: ./.docker/php
    volumes:
      - ./:/var/www/ecommerce
    links:
      - db
  # Configuration Nginx
  nginx:
    image: nginx
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/sites/:/etc/nginx/sites-available
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./:/var/www/ecommerce
    depends_on:
      - php
    ports:
      - "8089:8089"

volumes:
  db:
    driver: local