version: '3.8'

services:
  # Configuration MySQL
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3309:3309"
    environment:
      MYSQL_ROOT_PASSWORD: 4db4ea9f1
      MYSQL_USER: ecommerce_dev
      MYSQL_PASSWORD: 3c0mMerce
      MYSQL_DATABASE: ecommerce
      MYSQL_TCP_PORT: 3309
  # Configuration PHP
  php:
    container_name: ecommerce-app
    build:
      context: ./.docker/php
    volumes:
      - ./:/var/www/ecommerce
    links:
      - db
  # Configuration Nginx
  nginx:
    image: nginx
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/sites/:/etc/nginx/sites-available
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./:/var/www/ecommerce
    depends_on:
      - php
    ports:
      - "8089:8089"